-- Customer Data Templates Insert Script
-- Run this script in your Supabase SQL editor after running CUSTOMER_DATABASE_SETUP.sql
-- This script inserts all data templates with their groups

-- Note: The 'group' column should already be in the schema from CUSTOMER_DATABASE_SETUP.sql
-- If you're using an older version, uncomment the following lines:
-- ALTER TABLE customer_data_templates 
-- ADD COLUMN IF NOT EXISTS "group" VARCHAR(100);
-- CREATE INDEX IF NOT EXISTS idx_customer_data_templates_group ON customer_data_templates("group");

-- Insert all customer data templates
-- Note: Using ON CONFLICT DO NOTHING to prevent duplicates if script is run multiple times

-- #General Group
INSERT INTO customer_data_templates (title, key, "group") VALUES
    ('Phone Number = Business', 'phone_number_business', 'General'),
    ('Email = Business', 'email_business', 'General'),
    ('Location Name - Same as Business Name', 'location_name_same_as_business_name', 'General'),
    ('Location Address', 'location_address', 'General'),
    ('Street Address', 'street_address', 'General'),
    ('City', 'city', 'General'),
    ('State', 'state', 'General'),
    ('Postal Code', 'postal_code', 'General'),
    ('Country', 'country', 'General'),
    ('Website URL', 'website_url', 'General'),
    ('Business Hours - Open', 'business_hours_open', 'General'),
    ('Business Hours - Close', 'business_hours_close', 'General'),
    ('Business Hours - Days', 'business_hours_days', 'General'),
    ('Date Opened', 'date_opened', 'General'),
    ('Number of Employees', 'number_of_employees', 'General'),
    ('Payments Accepted', 'payments_accepted', 'General'),
    ('Google Profile', 'google_profile', 'General'),
    ('Facebook', 'facebook', 'General'),
    ('Instagram', 'instagram', 'General'),
    ('YouTube', 'youtube', 'General'),
    ('LinkedIn', 'linkedin', 'General'),
    ('Yelp', 'yelp', 'General'),
    ('Pinterest', 'pinterest', 'General'),
    ('Twitter', 'twitter', 'General'),
    ('Reddit', 'reddit', 'General'),
    ('TikTok', 'tiktok', 'General'),
    ('Primary Brand Color', 'primary_brand_color', 'General'),
    ('Primary Dark Brand Color', 'primary_dark_brand_color', 'General'),
    ('Brand Medium', 'brand_medium', 'General'),
    ('Form submission email', 'form_submission_email', 'General'),
    ('Google Analytics ID', 'google_analytics_id', 'General'),
    ('Google Tag Mgr ID', 'google_tag_mgr_id', 'General'),
    ('Facebook Tracking ID', 'facebook_tracking_id', 'General'),
    ('Any Other Tracking', 'any_other_tracking', 'General'),
    ('Where is your domain registered?', 'where_is_your_domain_registered', 'General'),
    ('Link to login', 'link_to_login', 'General'),
    ('Username', 'username', 'General'),
    ('Password', 'password', 'General'),
    ('GBP CID', 'gbp_cid', 'General'),
    ('Google Profile Embed', 'google_profile_embed', 'General')
ON CONFLICT (key) DO NOTHING;

-- #IMAGES Group
INSERT INTO customer_data_templates (title, key, "group") VALUES
    ('Logo', 'logo', 'IMAGES'),
    ('Logo White', 'logo_white', 'IMAGES'),
    ('Guarantee Graphic', 'guarantee_graphic', 'IMAGES'),
    ('Home Page Hero', 'home_page_hero', 'IMAGES'),
    ('Inner Page Default Hero Photo', 'inner_page_default_hero_photo', 'IMAGES'),
    ('Business Owner/s Photo', 'business_owner_s_photo', 'IMAGES'),
    ('Team Photo', 'team_photo', 'IMAGES'),
    ('Credibility Badge 1', 'credibility_badge_1', 'IMAGES'),
    ('Credibility Badge 2', 'credibility_badge_2', 'IMAGES'),
    ('Credibility Badge 3', 'credibility_badge_3', 'IMAGES'),
    ('Credibility Badge 4', 'credibility_badge_4', 'IMAGES'),
    ('Credibility Badge 5', 'credibility_badge_5', 'IMAGES'),
    ('Credibility Badge 6', 'credibility_badge_6', 'IMAGES'),
    ('FAQ Image', 'faq_image', 'IMAGES'),
    ('Fav Icon', 'fav_icon', 'IMAGES'),
    ('OG Share Image', 'og_share_image', 'IMAGES'),
    ('Service Area Hero Image', 'service_area_hero_image', 'IMAGES'),
    ('Badge Service Areas', 'badge_service_areas', 'IMAGES'),
    ('Review Badge 1', 'review_badge_1', 'IMAGES'),
    ('Review Badge 2', 'review_badge_2', 'IMAGES'),
    ('Review Badge 3', 'review_badge_3', 'IMAGES'),
    ('Review Badge 4', 'review_badge_4', 'IMAGES')
ON CONFLICT (key) DO NOTHING;

-- #SERVICES Group
INSERT INTO customer_data_templates (title, key, "group") VALUES
    ('Service 1 Name', 'service_1_name', 'SERVICES'),
    ('Service 1 Details', 'service_1_details', 'SERVICES'),
    ('Service 1 Target Keywords', 'service_1_target_keywords', 'SERVICES'),
    ('Service 1 Relevant Keywords', 'service_1_relevant_keywords', 'SERVICES'),
    ('Service 1 URL', 'service_1_url', 'SERVICES'),
    ('Service 1 Photo', 'service_1_photo', 'SERVICES'),
    ('Service 1 Short Description', 'service_1_short_description', 'SERVICES'),
    ('Service 1 Long Description', 'service_1_long_description', 'SERVICES'),
    ('Service 2 Name', 'service_2_name', 'SERVICES'),
    ('Service 2 Details', 'service_2_details', 'SERVICES'),
    ('Service 2 Target Keywords', 'service_2_target_keywords', 'SERVICES'),
    ('Service 2 Relevant Keywords', 'service_2_relevant_keywords', 'SERVICES'),
    ('Service 2 URL', 'service_2_url', 'SERVICES'),
    ('Service 2 Photo', 'service_2_photo', 'SERVICES'),
    ('Service 2 Short Description', 'service_2_short_description', 'SERVICES'),
    ('Service 2 Long Description', 'service_2_long_description', 'SERVICES'),
    ('Service 3 Name', 'service_3_name', 'SERVICES'),
    ('Service 3 Details', 'service_3_details', 'SERVICES'),
    ('Service 3 Target Keywords', 'service_3_target_keywords', 'SERVICES'),
    ('Service 3 Relevant Keywords', 'service_3_relevant_keywords', 'SERVICES'),
    ('Service 3 URL', 'service_3_url', 'SERVICES'),
    ('Service 3 Photo', 'service_3_photo', 'SERVICES'),
    ('Service 3 Short Description', 'service_3_short_description', 'SERVICES'),
    ('Service 3 Long Description', 'service_3_long_description', 'SERVICES'),
    ('Service 4 Name', 'service_4_name', 'SERVICES'),
    ('Service 4 Details', 'service_4_details', 'SERVICES'),
    ('Service 4 Target Keywords', 'service_4_target_keywords', 'SERVICES'),
    ('Service 4 Relevant Keywords', 'service_4_relevant_keywords', 'SERVICES'),
    ('Service 4 URL', 'service_4_url', 'SERVICES'),
    ('Service 4 Photo', 'service_4_photo', 'SERVICES'),
    ('Service 4 Short Description', 'service_4_short_description', 'SERVICES'),
    ('Service 4 Long Description', 'service_4_long_description', 'SERVICES'),
    ('Service 5 Name', 'service_5_name', 'SERVICES'),
    ('Service 5 Details', 'service_5_details', 'SERVICES'),
    ('Service 5 Target Keywords', 'service_5_target_keywords', 'SERVICES'),
    ('Service 5 Relevant Keywords', 'service_5_relevant_keywords', 'SERVICES'),
    ('Service 5 URL', 'service_5_url', 'SERVICES'),
    ('Service 5 Photo', 'service_5_photo', 'SERVICES'),
    ('Service 5 Short Description', 'service_5_short_description', 'SERVICES'),
    ('Service 5 Long Description', 'service_5_long_description', 'SERVICES'),
    ('Service 6 Name', 'service_6_name', 'SERVICES'),
    ('Service 6 Details', 'service_6_details', 'SERVICES'),
    ('Service 6 Target Keywords', 'service_6_target_keywords', 'SERVICES'),
    ('Service 6 Relevant Keywords', 'service_6_relevant_keywords', 'SERVICES'),
    ('Service 6 URL', 'service_6_url', 'SERVICES'),
    ('Service 6 Photo', 'service_6_photo', 'SERVICES'),
    ('Service 6 Short Description', 'service_6_short_description', 'SERVICES'),
    ('Service 6 Long Description', 'service_6_long_description', 'SERVICES')
ON CONFLICT (key) DO NOTHING;

-- #SERVICE AREAS Group
INSERT INTO customer_data_templates (title, key, "group") VALUES
    ('Service Area 1', 'service_area_1', 'SERVICE AREAS'),
    ('Service Area 1 URL', 'service_area_1_url', 'SERVICE AREAS'),
    ('Service Area 2', 'service_area_2', 'SERVICE AREAS'),
    ('Service Area 2 URL', 'service_area_2_url', 'SERVICE AREAS'),
    ('Service Area 3', 'service_area_3', 'SERVICE AREAS'),
    ('Service Area 3 URL', 'service_area_3_url', 'SERVICE AREAS'),
    ('Service Area 4', 'service_area_4', 'SERVICE AREAS'),
    ('Service Area 4 URL', 'service_area_4_url', 'SERVICE AREAS'),
    ('Service Area 5', 'service_area_5', 'SERVICE AREAS'),
    ('Service Area 5 URL', 'service_area_5_url', 'SERVICE AREAS'),
    ('Service Area 6', 'service_area_6', 'SERVICE AREAS'),
    ('Service Area 6 URL', 'service_area_6_url', 'SERVICE AREAS'),
    ('Service Area 7', 'service_area_7', 'SERVICE AREAS'),
    ('Service Area 7 URL', 'service_area_7_url', 'SERVICE AREAS'),
    ('Service Area 8', 'service_area_8', 'SERVICE AREAS'),
    ('Service Area 8 URL', 'service_area_8_url', 'SERVICE AREAS'),
    ('Service Area 9', 'service_area_9', 'SERVICE AREAS'),
    ('Service Area 9 URL', 'service_area_9_url', 'SERVICE AREAS'),
    ('Service Area 10', 'service_area_10', 'SERVICE AREAS'),
    ('Service Area 10 URL', 'service_area_10_url', 'SERVICE AREAS'),
    ('Service Area 11', 'service_area_11', 'SERVICE AREAS'),
    ('Service Area 11 URL', 'service_area_11_url', 'SERVICE AREAS'),
    ('Service Area 12', 'service_area_12', 'SERVICE AREAS'),
    ('Service Area 12 URL', 'service_area_12_url', 'SERVICE AREAS'),
    ('Service Area 13', 'service_area_13', 'SERVICE AREAS'),
    ('Service Area 13 URL', 'service_area_13_url', 'SERVICE AREAS'),
    ('Service Area 14', 'service_area_14', 'SERVICE AREAS'),
    ('Service Area 14 URL', 'service_area_14_url', 'SERVICE AREAS'),
    ('Service Area 15', 'service_area_15', 'SERVICE AREAS'),
    ('Service Area 15 URL', 'service_area_15_url', 'SERVICE AREAS'),
    ('Service Area 16', 'service_area_16', 'SERVICE AREAS'),
    ('Service Area 16 URL', 'service_area_16_url', 'SERVICE AREAS'),
    ('Service Area 17', 'service_area_17', 'SERVICE AREAS'),
    ('Service Area 17 URL', 'service_area_17_url', 'SERVICE AREAS'),
    ('Service Area 18', 'service_area_18', 'SERVICE AREAS'),
    ('Service Area 18 URL', 'service_area_18_url', 'SERVICE AREAS'),
    ('Service Area 19', 'service_area_19', 'SERVICE AREAS'),
    ('Service Area 19 URL', 'service_area_19_url', 'SERVICE AREAS'),
    ('Service Area 20', 'service_area_20', 'SERVICE AREAS'),
    ('Service Area 20 URL', 'service_area_20_url', 'SERVICE AREAS'),
    ('Additional Service Areas', 'additional_service_areas', 'SERVICE AREAS')
ON CONFLICT (key) DO NOTHING;

-- #WEBSITE CONTENT (Business Text) Group
INSERT INTO customer_data_templates (title, key, "group") VALUES
    ('About Us', 'about_us', 'WEBSITE CONTENT (Business Text)'),
    ('About Us Home Subhead', 'about_us_home_subhead', 'WEBSITE CONTENT (Business Text)'),
    ('CTA Footer', 'cta_footer', 'WEBSITE CONTENT (Business Text)'),
    ('Differentiator', 'differentiator', 'WEBSITE CONTENT (Business Text)'),
    ('Primary CTA', 'primary_cta', 'WEBSITE CONTENT (Business Text)'),
    ('Secondary CTA', 'secondary_cta', 'WEBSITE CONTENT (Business Text)'),
    ('Type of Business', 'type_of_business', 'WEBSITE CONTENT (Business Text)'),
    ('Type of Business Plural', 'type_of_business_plural', 'WEBSITE CONTENT (Business Text)'),
    ('Region', 'region', 'WEBSITE CONTENT (Business Text)'),
    ('Review Quote', 'review_quote', 'WEBSITE CONTENT (Business Text)'),
    ('Why Us 1: Title', 'why_us_1_title', 'WEBSITE CONTENT (Business Text)'),
    ('Why Us 1: Description', 'why_us_1_description', 'WEBSITE CONTENT (Business Text)'),
    ('Why Us 2: Title', 'why_us_2_title', 'WEBSITE CONTENT (Business Text)'),
    ('Why Us 2: Description', 'why_us_2_description', 'WEBSITE CONTENT (Business Text)'),
    ('Why Us 3: Title', 'why_us_3_title', 'WEBSITE CONTENT (Business Text)'),
    ('Why Us 3: Description', 'why_us_3_description', 'WEBSITE CONTENT (Business Text)')
ON CONFLICT (key) DO NOTHING;

-- #AI PROMPT CONTENT Group
INSERT INTO customer_data_templates (title, key, "group") VALUES
    ('Author', 'author', 'AI PROMPT CONTENT'),
    ('Business Category Target Keywords', 'business_category_target_keywords', 'AI PROMPT CONTENT'),
    ('Business Category Relevant Keywords', 'business_category_relevant_keywords', 'AI PROMPT CONTENT'),
    ('Target Audience', 'target_audience', 'AI PROMPT CONTENT'),
    ('Brand Voice', 'brand_voice', 'AI PROMPT CONTENT'),
    ('ABOUT US CONTENT', 'about_us_content', 'AI PROMPT CONTENT'),
    ('About: What do you do?', 'about_what_do_you_do', 'AI PROMPT CONTENT'),
    ('About: What makes you different?', 'about_what_makes_you_different', 'AI PROMPT CONTENT'),
    ('About: What are you dedicated to?', 'about_what_are_you_dedicated_to', 'AI PROMPT CONTENT'),
    ('About: What do you stand against?', 'about_what_do_you_stand_against', 'AI PROMPT CONTENT'),
    ('About: What problems do you solve?', 'about_what_problems_do_you_solve', 'AI PROMPT CONTENT'),
    ('About: Biggest benefit working with you?', 'about_biggest_benefit_working_with_you', 'AI PROMPT CONTENT'),
    ('About: Awards, credentials...', 'about_awards_credentials', 'AI PROMPT CONTENT'),
    ('About: Additional Business Information', 'about_additional_business_information', 'AI PROMPT CONTENT'),
    ('About: The Owner', 'about_the_owner', 'AI PROMPT CONTENT')
ON CONFLICT (key) DO NOTHING;

-- #TOPICS Group
INSERT INTO customer_data_templates (title, key, "group") VALUES
    ('Topic 1', 'topic_1', 'TOPICS'),
    ('Topic 1 Details', 'topic_1_details', 'TOPICS'),
    ('Topic 1 Target Keywords', 'topic_1_target_keywords', 'TOPICS'),
    ('Topic 1 Relevant Keywords', 'topic_1_relevant_keywords', 'TOPICS'),
    ('Topic 1 URL', 'topic_1_url', 'TOPICS'),
    ('Topic 1 Blog URL 1', 'topic_1_blog_url_1', 'TOPICS'),
    ('Topic 1 Blog URL 2', 'topic_1_blog_url_2', 'TOPICS'),
    ('Topic 1 Blog URL 3', 'topic_1_blog_url_3', 'TOPICS'),
    ('Topic 2', 'topic_2', 'TOPICS'),
    ('Topic 2 Details', 'topic_2_details', 'TOPICS'),
    ('Topic 2 Target Keywords', 'topic_2_target_keywords', 'TOPICS'),
    ('Topic 2 Relevant Keywords', 'topic_2_relevant_keywords', 'TOPICS'),
    ('Topic 2 URL', 'topic_2_url', 'TOPICS'),
    ('Topic 2 Blog URL 1', 'topic_2_blog_url_1', 'TOPICS'),
    ('Topic 2 Blog URL 2', 'topic_2_blog_url_2', 'TOPICS'),
    ('Topic 2 Blog URL 3', 'topic_2_blog_url_3', 'TOPICS'),
    ('Topic 3', 'topic_3', 'TOPICS'),
    ('Topic 3 Details', 'topic_3_details', 'TOPICS'),
    ('Topic 3 Target Keywords', 'topic_3_target_keywords', 'TOPICS'),
    ('Topic 3 Relevant Keywords', 'topic_3_relevant_keywords', 'TOPICS'),
    ('Topic 3 URL', 'topic_3_url', 'TOPICS'),
    ('Topic 3 Blog URL 1', 'topic_3_blog_url_1', 'TOPICS'),
    ('Topic 3 Blog URL 2', 'topic_3_blog_url_2', 'TOPICS'),
    ('Topic 3 Blog URL 3', 'topic_3_blog_url_3', 'TOPICS'),
    ('Topic 4', 'topic_4', 'TOPICS'),
    ('Topic 4 Details', 'topic_4_details', 'TOPICS'),
    ('Topic 4 Target Keywords', 'topic_4_target_keywords', 'TOPICS'),
    ('Topic 4 Relevant Keywords', 'topic_4_relevant_keywords', 'TOPICS'),
    ('Topic 4 URL', 'topic_4_url', 'TOPICS'),
    ('Topic 4 Blog URL 1', 'topic_4_blog_url_1', 'TOPICS'),
    ('Topic 4 Blog URL 2', 'topic_4_blog_url_2', 'TOPICS'),
    ('Topic 4 Blog URL 3', 'topic_4_blog_url_3', 'TOPICS'),
    ('Topic 5', 'topic_5', 'TOPICS'),
    ('Topic 5 Details', 'topic_5_details', 'TOPICS'),
    ('Topic 5 Target Keywords', 'topic_5_target_keywords', 'TOPICS'),
    ('Topic 5 Relevant Keywords', 'topic_5_relevant_keywords', 'TOPICS'),
    ('Topic 5 URL', 'topic_5_url', 'TOPICS'),
    ('Topic 5 Blog URL 1', 'topic_5_blog_url_1', 'TOPICS'),
    ('Topic 5 Blog URL 2', 'topic_5_blog_url_2', 'TOPICS'),
    ('Topic 5 Blog URL 3', 'topic_5_blog_url_3', 'TOPICS'),
    ('Topic 6', 'topic_6', 'TOPICS'),
    ('Topic 6 Details', 'topic_6_details', 'TOPICS'),
    ('Topic 6 Target Keywords', 'topic_6_target_keywords', 'TOPICS'),
    ('Topic 6 Relevant Keywords', 'topic_6_relevant_keywords', 'TOPICS'),
    ('Topic 6 URL', 'topic_6_url', 'TOPICS'),
    ('Topic 6 Blog URL 1', 'topic_6_blog_url_1', 'TOPICS'),
    ('Topic 6 Blog URL 2', 'topic_6_blog_url_2', 'TOPICS'),
    ('Topic 6 Blog URL 3', 'topic_6_blog_url_3', 'TOPICS'),
    ('Topic 7', 'topic_7', 'TOPICS'),
    ('Topic 7 Details', 'topic_7_details', 'TOPICS'),
    ('Topic 7 Target Keywords', 'topic_7_target_keywords', 'TOPICS'),
    ('Topic 7 Relevant Keywords', 'topic_7_relevant_keywords', 'TOPICS'),
    ('Topic 7 URL', 'topic_7_url', 'TOPICS'),
    ('Topic 7 Blog URL 1', 'topic_7_blog_url_1', 'TOPICS'),
    ('Topic 7 Blog URL 2', 'topic_7_blog_url_2', 'TOPICS'),
    ('Topic 7 Blog URL 3', 'topic_7_blog_url_3', 'TOPICS'),
    ('Topic 8', 'topic_8', 'TOPICS'),
    ('Topic 8 Details', 'topic_8_details', 'TOPICS'),
    ('Topic 8 Target Keywords', 'topic_8_target_keywords', 'TOPICS'),
    ('Topic 8 Relevant Keywords', 'topic_8_relevant_keywords', 'TOPICS'),
    ('Topic 8 URL', 'topic_8_url', 'TOPICS'),
    ('Topic 8 Blog URL 1', 'topic_8_blog_url_1', 'TOPICS'),
    ('Topic 8 Blog URL 2', 'topic_8_blog_url_2', 'TOPICS'),
    ('Topic 8 Blog URL 3', 'topic_8_blog_url_3', 'TOPICS'),
    ('Topic 9', 'topic_9', 'TOPICS'),
    ('Topic 9 Details', 'topic_9_details', 'TOPICS'),
    ('Topic 9 Target Keywords', 'topic_9_target_keywords', 'TOPICS'),
    ('Topic 9 Relevant Keywords', 'topic_9_relevant_keywords', 'TOPICS'),
    ('Topic 9 URL', 'topic_9_url', 'TOPICS'),
    ('Topic 9 Blog URL 1', 'topic_9_blog_url_1', 'TOPICS'),
    ('Topic 9 Blog URL 2', 'topic_9_blog_url_2', 'TOPICS'),
    ('Topic 9 Blog URL 3', 'topic_9_blog_url_3', 'TOPICS'),
    ('Topic 10', 'topic_10', 'TOPICS'),
    ('Topic 10 Details', 'topic_10_details', 'TOPICS'),
    ('Topic 10 Target Keywords', 'topic_10_target_keywords', 'TOPICS'),
    ('Topic 10 Relevant Keywords', 'topic_10_relevant_keywords', 'TOPICS'),
    ('Topic 10 URL', 'topic_10_url', 'TOPICS'),
    ('Topic 10 Blog URL 1', 'topic_10_blog_url_1', 'TOPICS'),
    ('Topic 10 Blog URL 2', 'topic_10_blog_url_2', 'TOPICS'),
    ('Topic 10 Blog URL 3', 'topic_10_blog_url_3', 'TOPICS')
ON CONFLICT (key) DO NOTHING;

-- Verify the insert
SELECT "group", COUNT(*) as count 
FROM customer_data_templates 
GROUP BY "group" 
ORDER BY "group";

